version: '3'


services:


  server:


    build: server/

    command: python ./server.py

    ports:
      - "8080:8080"



  client:
    build: client/

    command: cargo build
    command: cargo run

    network_mode: host

    depends_on:
      - server
